### ISSUE TITLE
M1 Mac Unable to Build Mattermost Container

### ISSUE THREAD

**Issue by jvanderaa** [nautobot/nautobot-chatops-cookiecutter#3]
### Environment
* Repo version:   0.1.0

### Observed Behavior

Error logged on baked cookie

### Expected Behavior

Containers are able to be built

### Steps to Reproduce
1. Use M1 Mac
2. `invoke build`

**Comment by jvanderaa** [comment]
A work around for this are:

https://github.com/psycopg/psycopg2/issues/1286#issuecomment-914286206

**Comment by bradh11** [comment]
i was able to get this working with the following code update to `Dockerfile-mattermost`.

```
ARG MYSQL_VER=5.7
FROM --platform=linux/amd64 mysql:${MYSQL_VER}

RUN yum update && yum install -y ca-certificates
```
